#ifndef _GAMESETTINGS_H_
#define _GAMESETTINGS_H_

#define	LENGTH_OF_SIDE 80
#define WIDTH 12
#define HEIGHT 8

#define INTERVAL_TIME 0.1

#define INITIAL_SUNSHINE 1000


/* Priority */
#define PRIORITY_OF_BOMB 4
#define	PRIORITY_OF_RABBIT 3
#define PRIORITY_OF_SHOOTER 2
#define PRIORITY_OF_PLANT 1

/* Plants */
#define	NUMBER_OF_PLANT 5
#define NO_PLANT 0
#define NUMBER_OF_PEASHOOTER 1
#define NUMBER_OF_CARROT 2
#define	NUMBER_OF_SUNFLOWER 3
#define NUMBER_OF_WALLNUT 4
#define NUMBER_OF_BLUEEGG 5

#define	HEALTH_POINT_OF_PEASHOOTER 70
#define PRICE_OF_PEASHOOTER 100
#define REFRIGERATE_TIME_OF_PEASHOTER 60

#define	HEALTH_POINT_OF_CARROT 70
#define PRICE_OF_CARROT 200
#define REFRIGERATE_TIME_OF_CARROT 60

#define	HEALTH_POINT_OF_SUNFLOWER 50
#define	PRICE_OF_SUNFLOWER 50
#define REFRIGERATE_TIME_OF_SUNFLOWER 40

#define HEALTH_POINT_OF_WALLNUT 200
#define PRICE_OF_WALLNUT 50
#define REFRIGERATE_TIME_OF_WALLNUT 200

#define HEALTH_POINT_OF_BLUEEGG 500
#define PRICE_OF_BLUEEGG 200
#define	REFRIGERATE_TIME_OF_BLUEEGG 250
#define ATTACK_OF_BLUEEGG 150



/* Things*/
#define FREQUENCE_OF_PEA 20
#define SPEED_OF_PEA 20
#define	ATTACK_OF_PEA 10

#define WORTH_OH_SUNSHINE 40
#define	FREQUENCE_OF_SUNSHINE 100
#define EXISTENCE_OF_SUNSHINE 70



/* Zombies */
#define	HEALTH_POINT_OF_ZOMBIE 90
#define	SPEED_OF_ZOMBIE 3
#define	ATTACK_OF_ZOMBIE 1

#define HEALTH_POINT_OF_EVILRABBIT 180
#define SPEED_OF_EVILRABBIT 2
#define ATTACK_OF_EVILRABBIT 2

#define NUMBER_OF_ZOMBIE_WAVE 4
#define CONTENT_OF_ZOMBIE_WAVE {{0, 0}, {2, 60}, {3, 40}, {4, 50}, {7, 40}}

#define NUMBER_OF_EVILRABBIT_WAVE 3
#define CONTENT_OF_EVILRABBIT_WAVE {{0, 0}, {2, 100}, {5, 50}, {3, 90}}



#endif